
    Keys.customKeys = {
        "backspace": "undo",
        "enter": "confirm",
        "esc": "break",
        "space": "draw",
        "left": "left",
        "up": "up",
        "right": "right",
        "down": "down",
        "0": "rotate",
        "1": "pencil",
        "2": "eraser",
        "3": "eyedropper",
        "4": "line",
        "5": "rectangle",
        "6": "parallelogram",
        "7": "polygon",
        "8": "ellipse",
        "9": "move",
        "f": "fill",
        "a": "left",
        "c" : "clipboard",
        "d": "right",
        "e": "clear",
        "m" : "minimize",
        "o": "focusOpacity",
        "p": "focusColor",
        "shift": "toggleDrawCursor",
        "s": "down",
        "t": "text",
        "w": "up",
        "+": "opacityUp",
        "-": "opacityDown",
        "F1": "toggleInfo",
        "F2": "toggleHelp",
        "F3": "toggleRecorder",
        "F4": "toggleKeys",
        "F5": "reload",
        "F6": "fileload",
        "F7": "getmatrix",
        "F8": "rec_edit",
        "F9": "openRecordFile",
        "F10": "saveRecordFile",
        "F11": "rec_rec",
        "ctrl + F11" : "rec_play",
        "ctrl + F12": "rec_stop",
        "ctrl + backspace" : "redo",
        "ctrl + b" : "backup",
        "ctrl + c" : "copy",
        "ctrl + d" : "destroy",
        "ctrl + r" : "restore",
        "ctrl + v" : "paste",
        "ctrl + x" : "remove",
        "ctrl + p" : "picker",
        "shift + c": "change-color",
        "alt + c": "clear-color",
        "shift + w": "color-bw",
        "shift + a": "color-area",
        "alt + a": "clear-area",
        "ctrl + k": "clone"
    };
